<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK1qzAF8\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK1qzAF8/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerK1qzAF8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerK1qzAF8\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerK1qzAF8\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'K1qzAF8',
    'container.build_id' => '1ec271ee',
    'container.build_time' => 1614874726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK1qzAF8');
