<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQIiaVxK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQIiaVxK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQIiaVxK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQIiaVxK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQIiaVxK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QIiaVxK',
    'container.build_id' => '80431b26',
    'container.build_time' => 1614978617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQIiaVxK');
