<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyp5f7V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyp5f7V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyp5f7V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyp5f7V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXyp5f7V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xyp5f7V',
    'container.build_id' => 'ba5b3d15',
    'container.build_time' => 1614900009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyp5f7V');
